# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('login_time', models.DateTimeField(verbose_name='登录时间')),
                ('nickname', models.CharField(max_length=15, verbose_name='昵称')),
                ('admin', models.CharField(max_length=10, verbose_name='身份')),
                ('sex', models.BooleanField()),
            ],
        ),
    ]
